### ISSUE TITLE
Dysfunctional Languages & Pairs

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/organisation#14]
These languages and pairs do not currently build, for various reasons.

### Languages
https://github.com/apertium/apertium-ady see https://github.com/apertium/apertium-ady/issues/2

https://github.com/apertium/apertium-ain segfaults when generating ain.autogen.bin

https://github.com/apertium/apertium-ckt see https://github.com/apertium/apertium-ckt/issues/1

https://github.com/apertium/apertium-ell see https://github.com/apertium/apertium-ell/issues/4

https://github.com/apertium/apertium-epo missing modes.xml and see https://github.com/apertium/apertium-epo/issues/2

https://github.com/apertium/apertium-gle has no modes.xml

https://github.com/apertium/apertium-lao is missing most things

https://github.com/apertium/apertium-mal errors out with: `.deps/mal.LR.lexc:24910.46-73: syntax error, unexpected ULSTRING, expecting LEXICON_NAME or ':': [near: `പീപ്പള്സ്']`

https://github.com/apertium/apertium-msa errors out with: `No rule to make target 'corpus/msa.tagged', needed by 'msa.prob'.`

https://github.com/apertium/apertium-nio errors out with: `The file .deps/nio.LR.lexc did not compile cleanly.`

https://github.com/apertium/apertium-pes has no configure.ac or modes.xml

https://github.com/apertium/apertium-quc has no configure.ac

https://github.com/apertium/apertium-snd has no configure.ac or modes.xml

https://github.com/apertium/apertium-trw errors out with: `.deps/trw.LR.lexc:309.10-16: syntax error, unexpected ULSTRING, expecting LEXICON_NAME or ':': [near: `پوخ']`

### Pairs
https://github.com/apertium/apertium-deu-dan errors out with: `deu-dan.autolex.bin: empty set of final states`

https://github.com/apertium/apertium-ell-eng blocked by broken apertium-ell

https://github.com/apertium/apertium-en-ga see https://github.com/apertium/apertium-en-ga/issues/1

https://github.com/apertium/apertium-en-pl see https://github.com/apertium/apertium-en-pl/issues/2

https://github.com/apertium/apertium-eng-afr see https://github.com/apertium/apertium-eng-afr/issues/4

https://github.com/apertium/apertium-eng-pes blocked by broken apertium-pes

https://github.com/apertium/apertium-eo-ru blocked by broken apertium-epo

https://github.com/apertium/apertium-eus-fin see https://github.com/apertium/apertium-eus-fin/issues/1

https://github.com/apertium/apertium-fao-dan see https://github.com/apertium/apertium-fao-dan/issues/1

https://github.com/apertium/apertium-fin-udm errors out with: `.deps/fin.LR.lexc:19.7-9: syntax error, unexpected ULSTRING, expecting LEXICON_NAME: [near: `PX']`

https://github.com/apertium/apertium-it-pt see https://github.com/apertium/apertium-it-pt/issues/1

https://github.com/apertium/apertium-kpv-fin see https://github.com/apertium/apertium-kpv-fin/issues/1

https://github.com/apertium/apertium-kpv-mhr see https://github.com/apertium/apertium-kpv-mhr/issues/1

https://github.com/apertium/apertium-mal-eng blocked by broken apertium-mal

https://github.com/apertium/apertium-mlt-spa errors out with: `apertium-mlt-spa.mlt-spa.lrx:8: parser error : Specification mandates value for attribute fil`

https://github.com/apertium/apertium-mrj-fin errors out with: `.deps/fin.RL.lexc:769.11-18: syntax error, unexpected ULSTRING, expecting LEXICON_NAME or ':': [near: `V_ISTUA']`

https://github.com/apertium/apertium-oci-spa see https://github.com/apertium/apertium-oci-spa/issues/1

https://github.com/apertium/apertium-olo-fin errors out with: `.deps/olo.RL.lexc:115.14: syntax error, unexpected ERROR, expecting LEXICON_START or LEXICON_START_WRONG_CASE: [near: `%']`

https://github.com/apertium/apertium-pes-eng blocked by broken apertium-pes

* ...which just made me realize both https://github.com/apertium/apertium-eng-pes and https://github.com/apertium/apertium-pes-eng exist? Someone fix that.

https://github.com/apertium/apertium-quc-spa blocked by broken apertium-quc

https://github.com/apertium/apertium-snd-hin blocked by broken apertium-snd

https://github.com/apertium/apertium-spa-pol fails to validate the acx from https://github.com/apertium/apertium-pol

https://github.com/apertium/apertium-tgk-pes blocked by broken apertium-pes

https://github.com/apertium/apertium-tha-lao blocked by broken apertium-lao

https://github.com/apertium/apertium-tuk-tur see https://github.com/apertium/apertium-tuk-tur/issues/1

https://github.com/apertium/apertium-tur-aze errors out with: `010-exception_deye.fst: 21terminate called after throwing an instance of 'std::logic_error'`

https://github.com/apertium/apertium-tur-fin see https://github.com/apertium/apertium-tur-fin/issues/1

https://github.com/apertium/apertium-tzh-spa feels like most files were forgotten in a commit

https://github.com/apertium/apertium-urd-snd blocked by broken apertium-snd

https://github.com/apertium/apertium-urd-trw blocked by broken apertium-trw

**Comment by mr-martian** [comment]
I added the `--rebuild` option to apertium-init for almost exactly this purpose.

See
- https://github.com/apertium/apertium-gle/pull/1
- https://github.com/apertium/apertium-pes/pull/1
- https://github.com/apertium/apertium-snd/pull/1
for fixes and see
https://github.com/apertium/apertium-trw/issues/2
for a more specific problem description.

The entire contents of -lao appear to be a wordlist extracted from Wiktionary.

**Comment by jonorthwash** [comment]
> The entire contents of -lao appear to be a wordlist extracted from Wiktionary.

That can probably still be made to compile without too much effort.  But yeah, a lot of Apertium resources are like that :|

**Comment by TinoDidriksen** [comment]
> The entire contents of -lao appear to be a wordlist extracted from Wiktionary.

In itself that's fine, but we have apertium-tha-lao that's supposed to depend on it. I only included broken monolinguals that something else depends on.

**Comment by ftyers** [comment]
I fixed `ell` and `trw`, `ain` appears to be a fork. `ckt` needs replacing with some other code.

**Comment by ftyers** [comment]
Fixed `ell-eng`.

**Comment by mr-martian** [comment]
`-epo` should be fixed now

**Comment by mr-martian** [comment]
eng-pol, ita-por, eng-afr, and eng-gle should be fixed now

**Comment by mr-martian** [comment]
Due to -pes having been fixed, eng-pes now works. pes-eng, however, is still broken due to an invalid transfer file.
